services:
  - type: web
    name: ai-agent-service
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python api/server.py
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false
      - key: PORT
        value: 10000
    plan: free
